/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo2_meet1;

/**
 *
 * @author ihsanfrr
 */
public class Pbo2_meet2_latihan7 extends javax.swing.JFrame {

    /**
     * Creates new form Pbo2_meet2_latihan7
     */
    public Pbo2_meet2_latihan7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaField = new javax.swing.JTextArea();
        btnChartAt = new javax.swing.JButton();
        btnIndexOf = new javax.swing.JButton();
        btnSubstring = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaField.setColumns(20);
        textAreaField.setRows(5);
        jScrollPane1.setViewportView(textAreaField);

        btnChartAt.setText("CharAt");
        btnChartAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChartAtActionPerformed(evt);
            }
        });

        btnIndexOf.setText("IndexOf");
        btnIndexOf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexOfActionPerformed(evt);
            }
        });

        btnSubstring.setText("Substring");
        btnSubstring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubstringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnChartAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIndexOf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubstring, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChartAt)
                        .addGap(18, 18, 18)
                        .addComponent(btnIndexOf)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubstring))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChartAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChartAtActionPerformed
        String result = "";
        String target = "IHSAN";
        int length = target.length();
        
        for(int i = 0; i < length; i++) {
            result += "Char at-" + i + "=" + target.charAt(i) + "\n";
        }
        
        textAreaField.setText("");
        textAreaField.append(result);
    }//GEN-LAST:event_btnChartAtActionPerformed

    private void btnIndexOfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexOfActionPerformed
        String target = "IHSAN";
        String nextTarget = "IH";
        String lastTarget = "SAN";
        
        textAreaField.setText("");
        textAreaField.append("String :" + target + "\n");
        textAreaField.append("String \"" + nextTarget + "\" at index = " + target.indexOf(nextTarget) + "\n");
        textAreaField.append("String \"" + lastTarget + "\" at index = " + target.indexOf(lastTarget) + "\n"); 
    }//GEN-LAST:event_btnIndexOfActionPerformed

    private void btnSubstringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubstringActionPerformed
        String result = "";
        String target = "IHSAN";
        int length = target.length();
        
        for(int i = 0; i < length; i++) {
            result += "IHSAN.substring("+i+")=" + target.substring(i) + "\n";
        }
        
        textAreaField.setText("");
        textAreaField.append(result);
    }//GEN-LAST:event_btnSubstringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pbo2_meet2_latihan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pbo2_meet2_latihan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pbo2_meet2_latihan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pbo2_meet2_latihan7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pbo2_meet2_latihan7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChartAt;
    private javax.swing.JButton btnIndexOf;
    private javax.swing.JButton btnSubstring;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaField;
    // End of variables declaration//GEN-END:variables
}
